# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13OrQ3f6Pttzf1l-44ZTQ0rHzrT9v4vz7
"""

import sys

try:
    import gradio
except ImportError:
    print("Installing gradio")
    !pip install gradio
    import gradio

import requests
import gradio as gr
def predict(feature1, feature2):
  # Your API endpoint URL
  api_url = " https://4cca-34-46-4-203.ngrok-free.app"  # Replace with your actual API endpoint

  # Prepare data for the API request
  data = {"feature1": feature1, "feature2": feature2}

  # Send the POST request to the API
  response = requests.post(api_url, json=data)

  # Check for successful response
  if response.status_code == 200:
    return response.json()["prediction"]
  else:
    return f"Error: {response.status_code}"

iface = gr.Interface(fn=predict, inputs=["number", "number"], outputs="text")
iface.launch()